Models/FacultyMember.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web_prog_Project.Models
{
    public class FacultyMember
    {
        [Key]
        public int FacultyMemberId { get; set; }

        [Required]
        [DisplayName("First Name")]
        [MaxLength(30)]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        [MaxLength(30)]
        public string LastName { get; set; }

        [Phone]
        [DisplayName("Phone Number")]
        public string Phone { get; set; }

        [DisplayName("Email Address")]
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string? Email { get; set; }
        [ForeignKey("Email")]
        public ApplicationUser? User { get; set; }

        // Foreign Key for Department
        [Required]
        public int DepartmentId { get; set; }
    }
}

Controllers/FacultyMemberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_prog_Project.Data;
using Web_prog_Project.Models.ViewModels;
using Web_prog_Project.Models;
using Microsoft.AspNetCore.Identity;


namespace Web_prog_Project.Controllers
{
    public class FacultyMemberController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;


        public FacultyMemberController(ApplicationDbContext db,UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
                var facultyMembers = await _db.FacultyMembers
                 .Join(
                     _db.Departments,
                     fm => fm.DepartmentId,
                     d => d.DepartmentId,
                     (fm, d) => new FacultyMemberWithDepartment
                     {
                         FacultyMemberId = fm.FacultyMemberId,
                         FirstName = fm.FirstName,
                         LastName = fm.LastName,
                         Phone = fm.Phone,
                         Email = fm.Email,
                         DepartmentName = d.Name
                     }
                 )
                 .ToListAsync();

            return View(facultyMembers);
        }

        public IActionResult Create()
        {
            ViewData["Departments"] = _db.Departments.Select(d => new SelectListItem
            {
                Value = d.DepartmentId.ToString(),
                Text = d.Name
            }).ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FacultyMember obj)
        {
            if (string.IsNullOrWhiteSpace(obj.Email))
            {
                ModelState.AddModelError("Email", "Email is required.");
            }

            if (ModelState.IsValid)
            {
                string password = obj.Email.Substring(0, obj.Email.IndexOf('@'));
                var user = new ApplicationUser
                {
                    UserName = obj.FirstName, 
                    Email = obj.Email,
                    Name = $"{obj.FirstName} {obj.LastName}" 
                };
                var result = await _userManager.CreateAsync(user, password);
                if (result.Succeeded)
                {
                    _db.FacultyMembers.Add(obj);
                    await _db.SaveChangesAsync();
                    await _userManager.AddToRoleAsync(user, "Doctor");
                    TempData["success"] = "Faculty member created successfully";
                    return RedirectToAction("Index");
                }
                   
            }

            ViewData["Departments"] = _db.Departments.Select(d => new SelectListItem
            {
                Value = d.DepartmentId.ToString(),
                Text = d.Name
            }).ToList();

            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            var facultyMember = _db.FacultyMembers
                .FirstOrDefault(f => f.FacultyMemberId == id);
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var departments = _db.Departments
                .Select(d => new SelectListItem
                {
                    Value = d.DepartmentId.ToString(),
                    Text = d.Name
                }).ToList();



            ViewData["Departments"] = _db.Departments.Select(d => new SelectListItem
            {
                Value = d.DepartmentId.ToString(),
                Text = d.Name
            }).ToList();

            return View(facultyMember);
        }

        [HttpPost]
        public IActionResult Edit(FacultyMember obj)
        {

            if (ModelState.IsValid)
            {
                var facultyMember = _db.FacultyMembers
           .FirstOrDefault(f => f.FacultyMemberId == obj.FacultyMemberId); 

                if (facultyMember != null)
                {
                    facultyMember.FirstName = obj.FirstName;
                    facultyMember.LastName = obj.LastName;
                    facultyMember.Phone = obj.Phone;
                    facultyMember.Email = obj.Email;
                    facultyMember.DepartmentId = obj.DepartmentId; 

                    var user = _userManager.FindByEmailAsync(obj.Email).Result;
                    if (user != null)
                    {
                        user.Name = $"{obj.FirstName} {obj.LastName}";
                        user.UserName = $"{obj.FirstName}";
                        var updateResult = _userManager.UpdateAsync(user).Result;

                        if (updateResult.Succeeded)
                        {
                            _db.SaveChanges();
                            TempData["success"] = "Faculty Member updated successfully";
                            return RedirectToAction("Index");
                        }
                    }
                            
                }

            }

            ViewData["Departments"] = _db.Departments.Select(d => new SelectListItem
            {
                Value = d.DepartmentId.ToString(),
                Text = d.Name
            }).ToList();

            return View();
        }

        public IActionResult Delete(int? id)
        {
            var facultyMember = _db.FacultyMembers
                    .FirstOrDefault(f => f.FacultyMemberId == id);
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var departmentName = _db.Departments
                .Where(d => d.DepartmentId == facultyMember.DepartmentId)
                .Select(d => d.Name) 
                .FirstOrDefault();

            // Create the view model to pass to the view
            var viewModel = new FacultyMemberWithDepartment
            {
                FacultyMemberId = facultyMember.FacultyMemberId,
                FirstName = facultyMember.FirstName,
                LastName = facultyMember.LastName,
                DepartmentName = departmentName, 
                Phone = facultyMember.Phone,
                Email = facultyMember.Email
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            FacultyMember? obj = _db.FacultyMembers.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
          
            var user = _userManager.FindByEmailAsync(obj.Email).Result;
            if (user != null)
            {
                var appointments = _db.Appointments.Where(a => a.DoctorId == user.Id).ToList();
                if (appointments.Any())
                {
                    _db.Appointments.RemoveRange(appointments);
                }

                _db.FacultyMembers.Remove(obj);
                _db.SaveChanges();

                _userManager.RemoveFromRoleAsync(user, "Faculty Member").Wait();

                var result = _userManager.DeleteAsync(user).Result;
                if (result.Succeeded)
                {              
                    TempData["success"] = "Faculty Member and associated user deleted successfully";
                    return RedirectToAction("Index");
                }


            }

            TempData["error"] = "User not found.";
            return RedirectToAction("Index");

        }
    }
}

Views/FacultyMember/Create.cshtml
@model Web_prog_Project.Models.FacultyMember


<form method="post">

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Faculty Member</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <!-- Department Dropdown -->
        <div class="mb-3 row p-1">
            <label asp-for="DepartmentId" class="form-label">Department</label>
            <select asp-for="DepartmentId" asp-items="@(ViewData["Departments"] as List<SelectListItem>)" class="form-control">
                <option value="">-- Select Department --</option>
            </select>
            <span asp-validation-for="DepartmentId" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Phone" class="p-0"></label>
            <input asp-for="Phone" class="form-control" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Email" class="p-0"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="FacultyMember" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/FacultyMember/Delete.cshtml
@model Web_prog_Project.Models.ViewModels.FacultyMemberWithDepartment


<form method="post">
    <input asp-for="FacultyMemberId" type="hidden" />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Faculty Member</h2>
            <hr />
        </div>
        <div class="mb-3">
            <p class="text-warning">Are you sure you want to delete this faculty member? This action cannot be undone.</p>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" disabled class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" disabled class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="DepartmentName" class="p-0">Department</label>
            <input asp-for="DepartmentName" disabled class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Phone" class="p-0"></label>
            <input asp-for="Phone" disabled class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Email" class="p-0"></label>
            <input asp-for="Email" disabled class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="FacultyMember" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

Views/FacultyMember/Edit.cshtml
@model Web_prog_Project.Models.FacultyMember


<form method="post">
    <input asp-for="FacultyMemberId" type="hidden" />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Faculty Member</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <!-- Department Dropdown -->
        <div class="mb-3 row p-1">
            <label asp-for="DepartmentId" class="form-label">Department</label>
            <select asp-for="DepartmentId" asp-items="@(ViewData["Departments"] as List<SelectListItem>)" class="form-control">
            </select>
            <span asp-validation-for="DepartmentId" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Phone" class="p-0"></label>
            <input asp-for="Phone" class="form-control" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Email" class="p-0"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="FacultyMember" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>

    </div>
</form>

Views/FacultyMember/Index.cshtml
@model IEnumerable<Web_prog_Project.Models.ViewModels.FacultyMemberWithDepartment>

@{
    ViewBag.Title = "Faculty Member";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row pt-4">
        <div class="col-md-6">
            <h2 class="text-primary">
                Faculty Members List
            </h2>
        </div>
        @if (User.IsInRole(Web_prog_Project.Utility.Helper.Admin))
        {
            <div class="col-md-6 text-end">
                <a asp-controller="FacultyMember" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> Add New Faculty Member
                </a>
            </div>
        }
    </div>

    <div class="table-responsive mt-3">
        <table class="table table-hover align-middle text-center">
            <thead class="table-primary">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Department</th>
                    <th>Phone</th>
                    <th>Email</th>
                    @if (User.IsInRole(Web_prog_Project.Utility.Helper.Admin))
                    {
                        <th>Actions</th>
                    }
                </tr>
            </thead>
            @if ((User.IsInRole(Web_prog_Project.Utility.Helper.Admin) || User.IsInRole(Web_prog_Project.Utility.Helper.Assistant) || User.IsInRole(Web_prog_Project.Utility.Helper.Doctor)))
            {
                <tbody>
                    @foreach (var obj in Model)
                    {
                        <tr>
                            <td>@obj.FirstName</td>
                            <td>@obj.LastName</td>
                            <td>@obj.DepartmentName</td>
                            <td>@obj.Phone</td>
                            <td>@obj.Email</td>
                            @if (User.IsInRole(Web_prog_Project.Utility.Helper.Admin))
                            {
                                <td>
                                    <div class="d-flex justify-content-center">
                                        <a asp-controller="FacultyMember" asp-action="Edit" asp-route-id="@obj.FacultyMemberId" class="btn btn-sm btn-primary mx-1">
                                            <i class="bi bi-pencil-square"></i> Edit
                                        </a>
                                        <a asp-controller="FacultyMember" asp-action="Delete" asp-route-id="@obj.FacultyMemberId" class="btn btn-sm btn-danger mx-1">
                                            <i class="bi bi-trash-fill"></i> Delete
                                        </a>
                                    </div>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            }
           
        </table>
    </div>
</div>